version: '3'

services:

  mysql_chat:
    container_name: mysql_chat
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat_db
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2
    ports:
      - '1306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php_fpm_chat:
    build:
      context: ../docker/php-fpm
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:secret@mysql_chat:3306/chat_db?serverVersion=8
    container_name: php_fpm_chat
    restart: unless-stopped
    volumes:
      - ../src:/var/www
      - ../data/lib/uploads:/var/www/public/uploads
      - ./main-local.php:/var/www/config/main-local.php
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysql_chat
    links:
      - mysql_chat
  nginx_chat:
    build:
      context: ../docker/nginx
    volumes:
      - ../src:/var/www
      - ../data/lib/uploads:/var/www/public/uploads
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/nginx/sites/:/etc/nginx/sites-available
      - ../docker/nginx/conf.d/:/etc/nginx/conf.d
      - ../docker/logs:/var/log
      - ../docker/nginx/ssl:/etc/nginx/ssl
    container_name: nginx_chat
    restart: unless-stopped
    depends_on:
      - php_fpm_chat
    ports:
      - "4488:443"
